### ISSUE TITLE
doxygen : Can I remove doxygen document with @cond?

### ISSUE THREAD

**Issue by 1434cga** [1434cga/CGADoxygen#9]
EXTRACT_ALL = NO
HIDE_NODOC_CLASS = YES

Verify whether it makes doxygen documents or not   when we use @cond
210     /**
211      * @cond TTT
212      *   test
213     *  @endcond
214      */

result : make doxygen documents without any comments in /** */
So we should remove /** */ not to show doxygen documents

Could we support to remove the doxygen documents when contents is empty?

**Comment by cheoljoo** [comment]
- That's right.  we can remove the doxygen when @cond tag is not in Doxyfile.
- But, This function will have the doxygen comments in html doxygen without any contents.   they will have empty contents in doxygen web and perlmod. 
 - **So we can skip the comments if content is empty.**
